language: objective-c
osx_image: xcode11.3
xcode_project: frameworks/SwiftlyCache.xcodeproj
xcode_scheme: SwiftlyCache

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version